Vagrant.configure("2") do |config|
	#config.vm.box = "szabacsik/ubuntu"
    config.vm.box = ".\\output\\ubuntu-18.04.2.box"
	#config.vm.box_version = "0.0.1"
	config.vm.provider "virtualbox"
	config.vm.network "private_network", type: "dhcp"
	#config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.hostname = "ubuntu"
	#config.vm.synced_folder ".", "/attached", :mount_options => ["dmode=777", "fmode=666"]
	config.ssh.username="vagrant"
	config.ssh.password="vagrant"
	#Optional NFS. Make sure to remove other synced_folder line too
	#config.vm.synced_folder ".", "/attached", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
end
